-- lua/plugins/themes.lua
return {
	{ "catppuccin/nvim", name = "catppuccin" },
	"dracula/vim",
	{ "Everblush/nvim", name = "everblush" },
	"self:ainnhe/everforest",
	"projekt0n/github-nvim-theme",
	"morhetz/gruvbox",
	"rebelot/kanagawa.nvim",
	"savq/melange-nvim",
	"marko-cerovac/material.nvim",
	"ramojus/mellifluous.nvim",
	"mellow-theme/mellow.nvim",
	"xero/miasma.nvim",
	"tanvirtin/monokai.nvim",
	"bluz71/vim-moonfly-colors",
	{ "rose-pine/neovim", name = "rose-pine" },
	"oxfist/night-owl.nvim",
	"EdenEast/nightfox.nvim",
	"shaunsingh/nord.nvim",
	"olimorris/onedarkpro.nvim",
	"nyoom-engineering/oxocarbon.nvim",
	"drewtempelmeyer/palenight.vim",
	"folke/tokyonight.nvim",
	"glepnir/zephyr-nvim",
}
